# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default='Some Text', max_length=200, unique=True),
        ),
    ]
